export const data = [
  {
    "id": "To Do",
    "title": "To Do",
    "cards": [
      {
        "__typename": "tasksEdge",
        "node": {
          "__typename": "tasks",
          "id": "42",
          "user_id": "615c1bb2-973a-4da5-936f-71de513ef4f7",
          "created_at": "2024-03-25T08:37:09.179514+00:00",
          "title": "🔍 Test Samarit",
          "description": "Checking how Samarit works within our setup.",
          "updated_at": null,
          "due_date": null,
          "priority": 0,
          "assigned_to": null,
          "labels": null,
          "completed_at": null,
          "is_archived": null,
          "status": "1",
        },
      },
      {
        "__typename": "tasksEdge",
        "node": {
          "__typename": "tasks",
          "id": "43",
          "user_id": "615c1bb2-973a-4da5-936f-71de513ef4f7",
          "created_at": "2024-03-25T08:37:09.604323+00:00",
          "title": "🛠 Test CrayTask Functions",
          "description":
            "Evaluating how CrayTask functions operate in our environment.",
          "updated_at": null,
          "due_date": null,
          "priority": 0,
          "assigned_to": null,
          "labels": null,
          "completed_at": null,
          "is_archived": null,
          "status": "1",
        },
      },
      {
        "__typename": "tasksEdge",
        "node": {
          "__typename": "tasks",
          "id": "44",
          "user_id": "615c1bb2-973a-4da5-936f-71de513ef4f7",
          "created_at": "2024-03-25T08:37:10.010518+00:00",
          "title": "📦 Test CrayTroom Functions",
          "description":
            "Assessing the functionality of CrayTroom within our system.",
          "updated_at": null,
          "due_date": null,
          "priority": 0,
          "assigned_to": null,
          "labels": null,
          "completed_at": null,
          "is_archived": null,
          "status": "1",
        },
      },
      {
        "__typename": "tasksEdge",
        "node": {
          "__typename": "tasks",
          "id": "45",
          "user_id": "615c1bb2-973a-4da5-936f-71de513ef4f7",
          "created_at": "2024-03-25T08:37:10.183227+00:00",
          "title": "🔧 Create Room Filter",
          "description":
            "Developing a filter for each room to have its own ACT.",
          "updated_at": null,
          "due_date": null,
          "priority": 0,
          "assigned_to": null,
          "labels": null,
          "completed_at": null,
          "is_archived": null,
          "status": "1",
        },
      },
      {
        "__typename": "tasksEdge",
        "node": {
          "__typename": "tasks",
          "id": "46",
          "user_id": "1fd7563e-e694-4fff-bdb7-621ffc25dab4",
          "created_at": "2024-03-25T10:45:42.50684+00:00",
          "title": "Deploy",
          "description": "Vercel",
          "updated_at": null,
          "due_date": null,
          "priority": 0,
          "assigned_to": null,
          "labels": null,
          "completed_at": null,
          "is_archived": null,
          "status": "1",
        },
      },
      {
        "__typename": "tasksEdge",
        "node": {
          "__typename": "tasks",
          "id": "47",
          "user_id": "615c1bb2-973a-4da5-936f-71de513ef4f7",
          "created_at": "2024-03-25T10:51:57.861895+00:00",
          "title": "🔄 Implement Logout Functionality",
          "description":
            "Ensure the logout button properly logs the user out and redirects them to the appropriate screen.",
          "updated_at": null,
          "due_date": null,
          "priority": 0,
          "assigned_to": null,
          "labels": null,
          "completed_at": null,
          "is_archived": null,
          "status": "1",
        },
      },
      {
        "__typename": "tasksEdge",
        "node": {
          "__typename": "tasks",
          "id": "48",
          "user_id": "615c1bb2-973a-4da5-936f-71de513ef4f7",
          "created_at": "2024-03-25T10:51:58.288183+00:00",
          "title": "🔑 Add Promo Code Feature",
          "description":
            "Implement a feature allowing users to enter a promo code. Ensure the header is hidden and input style is set correctly.",
          "updated_at": null,
          "due_date": null,
          "priority": 0,
          "assigned_to": null,
          "labels": null,
          "completed_at": null,
          "is_archived": null,
          "status": "1",
        },
      },
      {
        "__typename": "tasksEdge",
        "node": {
          "__typename": "tasks",
          "id": "49",
          "user_id": "615c1bb2-973a-4da5-936f-71de513ef4f7",
          "created_at": "2024-03-25T10:51:58.460401+00:00",
          "title": "🎥 Auto-Add Video",
          "description":
            "Ensure videos are automatically added based on user selection.",
          "updated_at": null,
          "due_date": null,
          "priority": 0,
          "assigned_to": null,
          "labels": null,
          "completed_at": null,
          "is_archived": null,
          "status": "1",
        },
      },
      {
        "__typename": "tasksEdge",
        "node": {
          "__typename": "tasks",
          "id": "50",
          "user_id": "615c1bb2-973a-4da5-936f-71de513ef4f7",
          "created_at": "2024-03-25T10:51:58.63613+00:00",
          "title": "🔄 Update Main Picture",
          "description":
            "Change the main picture on the platform and add a greeting message.",
          "updated_at": null,
          "due_date": null,
          "priority": 0,
          "assigned_to": null,
          "labels": null,
          "completed_at": null,
          "is_archived": null,
          "status": "1",
        },
      },
      {
        "__typename": "tasksEdge",
        "node": {
          "__typename": "tasks",
          "id": "51",
          "user_id": "615c1bb2-973a-4da5-936f-71de513ef4f7",
          "created_at": "2024-03-25T10:51:58.801344+00:00",
          "title": "🌌 Implement Cosmos Feature",
          "description":
            "Create a feature where the cosmos can be interactively spun by the user.",
          "updated_at": null,
          "due_date": null,
          "priority": 0,
          "assigned_to": null,
          "labels": null,
          "completed_at": null,
          "is_archived": null,
          "status": "1",
        },
      },
      {
        "__typename": "tasksEdge",
        "node": {
          "__typename": "tasks",
          "id": "52",
          "user_id": "615c1bb2-973a-4da5-936f-71de513ef4f7",
          "created_at": "2024-03-25T10:51:58.97494+00:00",
          "title": "🛠 Fix Mutation Issue",
          "description": "Resolve the problem causing mutations to fail.",
          "updated_at": null,
          "due_date": null,
          "priority": 0,
          "assigned_to": null,
          "labels": null,
          "completed_at": null,
          "is_archived": null,
          "status": "1",
        },
      },
      {
        "__typename": "tasksEdge",
        "node": {
          "__typename": "tasks",
          "id": "53",
          "user_id": "615c1bb2-973a-4da5-936f-71de513ef4f7",
          "created_at": "2024-03-25T10:51:59.182248+00:00",
          "title": "🚀 Implement Feature Flags",
          "description":
            "Develop a system for feature flags to enable or disable features dynamically.",
          "updated_at": null,
          "due_date": null,
          "priority": 0,
          "assigned_to": null,
          "labels": null,
          "completed_at": null,
          "is_archived": null,
          "status": "1",
        },
      },
      {
        "__typename": "tasksEdge",
        "node": {
          "__typename": "tasks",
          "id": "54",
          "user_id": "615c1bb2-973a-4da5-936f-71de513ef4f7",
          "created_at": "2024-03-25T10:51:59.347475+00:00",
          "title": "🧹 Refactor useSuperbase and useWeb3Alpha",
          "description":
            "Remove unused logic from useSuperbase and useWeb3Alpha hooks, leaving only essential functions.",
          "updated_at": null,
          "due_date": null,
          "priority": 0,
          "assigned_to": null,
          "labels": null,
          "completed_at": null,
          "is_archived": null,
          "status": "1",
        },
      },
      {
        "__typename": "tasksEdge",
        "node": {
          "__typename": "tasks",
          "id": "55",
          "user_id": "615c1bb2-973a-4da5-936f-71de513ef4f7",
          "created_at": "2024-03-25T10:51:59.773617+00:00",
          "title": "🔍 Implement GraphQuery",
          "description":
            "Ensure GraphQuery works with all connections, methods, and iterations without issues.",
          "updated_at": null,
          "due_date": null,
          "priority": 0,
          "assigned_to": null,
          "labels": null,
          "completed_at": null,
          "is_archived": null,
          "status": "1",
        },
      },
      {
        "__typename": "tasksEdge",
        "node": {
          "__typename": "tasks",
          "id": "56",
          "user_id": "615c1bb2-973a-4da5-936f-71de513ef4f7",
          "created_at": "2024-03-25T10:52:00.207366+00:00",
          "title": "📊 Kanban Task Management",
          "description":
            "Implement task management using D&D Kit for drag and drop functionality in the Kanban board.",
          "updated_at": null,
          "due_date": null,
          "priority": 0,
          "assigned_to": null,
          "labels": null,
          "completed_at": null,
          "is_archived": null,
          "status": "1",
        },
      },
      {
        "__typename": "tasksEdge",
        "node": {
          "__typename": "tasks",
          "id": "57",
          "user_id": "615c1bb2-973a-4da5-936f-71de513ef4f7",
          "created_at": "2024-03-25T10:52:00.654934+00:00",
          "title": "🔧 Fix Review Status Update",
          "description":
            "Resolve the issue where the review status does not update correctly in the Kanban board.",
          "updated_at": null,
          "due_date": null,
          "priority": 0,
          "assigned_to": null,
          "labels": null,
          "completed_at": null,
          "is_archived": null,
          "status": "1",
        },
      },
      {
        "__typename": "tasksEdge",
        "node": {
          "__typename": "tasks",
          "id": "58",
          "user_id": "615c1bb2-973a-4da5-936f-71de513ef4f7",
          "created_at": "2024-03-25T10:52:00.825126+00:00",
          "title": "📝 Create Room Selection Feature",
          "description":
            "Develop a feature allowing users to select and filter conversations by room.",
          "updated_at": null,
          "due_date": null,
          "priority": 0,
          "assigned_to": null,
          "labels": null,
          "completed_at": null,
          "is_archived": null,
          "status": "1",
        },
      },
      {
        "__typename": "tasksEdge",
        "node": {
          "__typename": "tasks",
          "id": "59",
          "user_id": "615c1bb2-973a-4da5-936f-71de513ef4f7",
          "created_at": "2024-03-25T13:28:26.969028+00:00",
          "title": "🎙️ Check Recording Attachment",
          "description":
            "Ensure the new recording is properly attached to the conference.",
          "updated_at": null,
          "due_date": null,
          "priority": 0,
          "assigned_to": null,
          "labels": null,
          "completed_at": null,
          "is_archived": null,
          "status": "1",
        },
      },
      {
        "__typename": "tasksEdge",
        "node": {
          "__typename": "tasks",
          "id": "60",
          "user_id": "615c1bb2-973a-4da5-936f-71de513ef4f7",
          "created_at": "2024-03-25T13:28:27.380848+00:00",
          "title": "🔄 Real-Time Update",
          "description": "Make a real-time update to the group in this spin.",
          "updated_at": null,
          "due_date": null,
          "priority": 0,
          "assigned_to": null,
          "labels": null,
          "completed_at": null,
          "is_archived": null,
          "status": "1",
        },
      },
      {
        "__typename": "tasksEdge",
        "node": {
          "__typename": "tasks",
          "id": "61",
          "user_id": "615c1bb2-973a-4da5-936f-71de513ef4f7",
          "created_at": "2024-03-25T13:28:27.806101+00:00",
          "title": "🚀 Deploy Site",
          "description": "Deploy the site for testing.",
          "updated_at": null,
          "due_date": null,
          "priority": 0,
          "assigned_to": null,
          "labels": null,
          "completed_at": null,
          "is_archived": null,
          "status": "1",
        },
      },
      {
        "__typename": "tasksEdge",
        "node": {
          "__typename": "tasks",
          "id": "62",
          "user_id": "615c1bb2-973a-4da5-936f-71de513ef4f7",
          "created_at": "2024-03-25T13:28:28.263342+00:00",
          "title": "🐞 Fix Bugs",
          "description": "Fix small bugs in the tasks.",
          "updated_at": null,
          "due_date": null,
          "priority": 0,
          "assigned_to": null,
          "labels": null,
          "completed_at": null,
          "is_archived": null,
          "status": "1",
        },
      },
      {
        "__typename": "tasksEdge",
        "node": {
          "__typename": "tasks",
          "id": "63",
          "user_id": "615c1bb2-973a-4da5-936f-71de513ef4f7",
          "created_at": "2024-03-25T13:28:28.705724+00:00",
          "title": "👥 Update Users",
          "description": "Update users to see what's broken there.",
          "updated_at": null,
          "due_date": null,
          "priority": 0,
          "assigned_to": null,
          "labels": null,
          "completed_at": null,
          "is_archived": null,
          "status": "1",
        },
      },
    ],
  },
  {
    "id": "In Progress",
    "title": "In Progress",
    "cards": [
      {
        "__typename": "tasksEdge",
        "node": {
          "__typename": "tasks",
          "id": "35",
          "user_id": "8af7f9af-7325-415b-8267-1cbe040bebfb",
          "created_at": "2024-03-22T17:02:40.700223+00:00",
          "title": "Edge Function ",
          "description": "Добавить функцию перевода",
          "updated_at": "2024-03-27T03:21:57.965+00:00",
          "due_date": null,
          "priority": 0,
          "assigned_to": null,
          "labels": null,
          "completed_at": null,
          "is_archived": null,
          "status": "2",
        },
      },
      {
        "__typename": "tasksEdge",
        "node": {
          "__typename": "tasks",
          "id": "36",
          "user_id": "ddf06531-a6e9-439c-977f-81411e06d459",
          "created_at": "2024-03-22T17:03:31.458578+00:00",
          "title": "Edge function",
          "description": "Эмодзи в тайтл",
          "updated_at": "2024-03-27T03:21:48.054+00:00",
          "due_date": null,
          "priority": 0,
          "assigned_to": null,
          "labels": null,
          "completed_at": null,
          "is_archived": null,
          "status": "2",
        },
      },
      {
        "__typename": "tasksEdge",
        "node": {
          "__typename": "tasks",
          "id": "37",
          "user_id": "e3939cb3-3198-4f52-8bfb-5728cc3dba84",
          "created_at": "2024-03-23T12:37:57.834795+00:00",
          "title": "Создать комнату",
          "description": "Реализовать функционал создания комнаты",
          "updated_at": "2024-03-27T03:13:11.219+00:00",
          "due_date": null,
          "priority": 0,
          "assigned_to": null,
          "labels": null,
          "completed_at": null,
          "is_archived": null,
          "status": "2",
        },
      },
      {
        "__typename": "tasksEdge",
        "node": {
          "__typename": "tasks",
          "id": "38",
          "user_id": "1e3eed35-27f7-4c0d-afd1-8befafc1befa",
          "created_at": "2024-03-23T13:56:27.878229+00:00",
          "title": "Связать таблицы",
          "description":
            "Объединить одним user_id схемы: Room assets, Workspace",
          "updated_at": "2024-03-25T11:28:38.435+00:00",
          "due_date": null,
          "priority": 0,
          "assigned_to": null,
          "labels": null,
          "completed_at": null,
          "is_archived": null,
          "status": "2",
        },
      },
      {
        "__typename": "tasksEdge",
        "node": {
          "__typename": "tasks",
          "id": "39",
          "user_id": "08dce09e-245c-4a39-97e3-f574981dfbd6",
          "created_at": "2024-03-23T13:59:04.551727+00:00",
          "title": "Loader",
          "description": "",
          "updated_at": "2024-03-27T03:13:14.235+00:00",
          "due_date": null,
          "priority": 0,
          "assigned_to": null,
          "labels": null,
          "completed_at": null,
          "is_archived": null,
          "status": "2",
        },
      },
      {
        "__typename": "tasksEdge",
        "node": {
          "__typename": "tasks",
          "id": "40",
          "user_id": "dd20f5ed-5b3d-44df-b4f9-1b03749a69de",
          "created_at": "2024-03-25T05:31:57.273109+00:00",
          "title": "Список комнат",
          "description": "Детали комнаты",
          "updated_at": "2024-03-27T03:07:58.34+00:00",
          "due_date": null,
          "priority": 0,
          "assigned_to": null,
          "labels": null,
          "completed_at": null,
          "is_archived": null,
          "status": "2",
        },
      },
      {
        "__typename": "tasksEdge",
        "node": {
          "__typename": "tasks",
          "id": "41",
          "user_id": "615c1bb2-973a-4da5-936f-71de513ef4f7",
          "created_at": "2024-03-25T08:37:08.75579+00:00",
          "title": "🔌 Connect RoomAssets",
          "description":
            "Connecting RoomAssets with our own rooms to test integration.",
          "updated_at": "2024-03-27T03:13:16.211+00:00",
          "due_date": null,
          "priority": 0,
          "assigned_to": null,
          "labels": null,
          "completed_at": null,
          "is_archived": null,
          "status": "2",
        },
      },
      {
        "__typename": "tasksEdge",
        "node": {
          "__typename": "tasks",
          "id": "64",
          "user_id": "615c1bb2-973a-4da5-936f-71de513ef4f7",
          "created_at": "2024-03-26T15:55:53.505083+00:00",
          "title": "🔍 Check Work Capacity",
          "description":
            "Verify the project's work capacity and ensure all functions are nearly completed.",
          "updated_at": "2024-03-27T03:13:19.27+00:00",
          "due_date": null,
          "priority": 0,
          "assigned_to": null,
          "labels": null,
          "completed_at": null,
          "is_archived": null,
          "status": "2",
        },
      },
    ],
  },
  {
    "id": "Review",
    "title": "Review",
    "cards": [{
      "__typename": "tasksEdge",
      "node": {
        "__typename": "tasks",
      },
    }],
  },
  {
    "id": "Done",
    "title": "Done",
    "cards": [{
      "__typename": "tasksEdge",
      "node": {
        "__typename": "tasks",
      },
    }],
  },
];
